### ISSUE TITLE
faraday-retry missing from gemspec dependencies

### ISSUE THREAD

**Issue by n-at-han-k** [team-telnyx/telnyx-ruby#97]
Please see the comment below from a previous issue.
The `faraday-retry` gem is missing from the gemspec.
Simply installing `telnyx` makes rails apps unbootable.
Running `bundle add faraday-retry` fixes this.

              @ADandyGuyInSpace I was setting up this gem in a new project and ran into a load error with this gem requiring `faraday/retry`. I believe `faraday-retry` needs to be added to as a dependency in `telnyx.gemspec`. Adding it to my own `Gemfile` resolved my load issue.

```
/usr/local/lib/ruby/3.3.0/bundled_gems.rb:75:in `require': cannot load such file -- faraday/retry (LoadError)
	from /usr/local/lib/ruby/3.3.0/bundled_gems.rb:75:in `block (2 levels) in replace_require'
	from /usr/local/bundle/gems/bootsnap-1.18.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:17:in `require'
	from /usr/local/bundle/gems/telnyx-3.0.3/lib/telnyx.rb:7:in `<main>'
```

_Originally posted by @daneshd in https://github.com/team-telnyx/telnyx-ruby/issues/83#issuecomment-2406050424_

**Comment by Talha5** [comment]
@n-at-han-k Did you get to fix it somehow? any workarounds?

**Comment by n-at-han-k** [comment]
> [@n-at-han-k](https://github.com/n-at-han-k) Did you get to fix it somehow? any workarounds?

If you read my comment, you'll see the solution.
